### ISSUE TITLE
横屏模式旋转到竖屏 闪退

### ISSUE THREAD

**Issue by androidcn** [liaoliao666/v2ex#69]
```
com.facebook.jni.CppException: Exception in HostFunction: java.lang.ClassNotFoundException: Could not retrieve ViewPager2 instance

[native code]
stopObservingProgress
stopObservingProgress@[native code]

step

forEach@[native code]


	at com.swmansion.reanimated.nativeProxy.AnimationFrameCallback.onAnimationFrame(Native Method)
	at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:248)
	at com.swmansion.reanimated.NodesManager.-$$Nest$monAnimationFrame(Unknown Source:0)
	at com.swmansion.reanimated.NodesManager$1.doFrameGuarded(NodesManager.java:143)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1449)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:998)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

**Comment by liaoliao666** [comment]
节后回来再研究

**Comment by androidcn** [comment]
> https://github.com/liaoliao666/v2ex/releases/download/1.5.2/build-1696511565411.apk
> 试试这个版本

```
com.facebook.jni.CppException: Exception in HostFunction: java.lang.ClassNotFoundException: Could not retrieve ViewPager2 instance

[native code]
stopObservingProgress
stopObservingProgress@[native code]

step

forEach@[native code]


	at com.swmansion.reanimated.nativeProxy.AnimationFrameCallback.onAnimationFrame(Native Method)
	at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:248)
	at com.swmansion.reanimated.NodesManager.-$$Nest$monAnimationFrame(Unknown Source:0)
	at com.swmansion.reanimated.NodesManager$1.doFrameGuarded(NodesManager.java:143)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1449)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:998)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

**Comment by liaoliao666** [comment]
还是闪退的么

**Comment by liaoliao666** [comment]
试试这个版本的
https://github.com/liaoliao666/v2ex/releases/download/1.5.3/build-1696524396206.apk

**Comment by androidcn** [comment]
> 试试这个版本的
> https://github.com/liaoliao666/v2ex/releases/download/1.5.3/build-1696524396206.apk

```
com.facebook.jni.CppException: Exception in HostFunction: java.lang.ClassNotFoundException: Could not retrieve ViewPager2 instance

[native code]
stopObservingProgress
stopObservingProgress@[native code]

step

forEach@[native code]


	at com.swmansion.reanimated.nativeProxy.AnimationFrameCallback.onAnimationFrame(Native Method)
	at com.swmansion.reanimated.NodesManager.onAnimationFrame(NodesManager.java:248)
	at com.swmansion.reanimated.NodesManager.-$$Nest$monAnimationFrame(Unknown Source:0)
	at com.swmansion.reanimated.NodesManager$1.doFrameGuarded(NodesManager.java:143)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1449)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:998)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8294)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

一样
